package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-linux-amd64/jdk8u112/7884/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, September 22, 2016 9:11:52 PM PDT
*/

public interface LIFESPAN_POLICY_ID
{

  /**
  	 * The value representing LIFESPAN_POLICY_ID.
  	 */
  public static final int value = (int)(17L);
}
